{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "colab_type": "text",
        "id": "view-in-github"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/rebornrulz/Rulz-AI/blob/main/wandfb/PandasAI_demo.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "8OnF6qsbDG1t"
      },
      "source": [
        "#PandasAI\n",
        "\n",
        "Pandas AI is a Python library that adds generative artificial intelligence capabilities to Pandas, the popular data analysis and manipulation tool.\n",
        "\n",
        "Here is a very simple demo about how it work!"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "-VQE9nGwDaiG"
      },
      "source": [
        "First of all we install the dependencies:"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "qtqSnCgwDDCg",
        "outputId": "a5893537-e167-496a-97bb-bfd22e1a8631"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Defaulting to user installation because normal site-packages is not writeable\n",
            "Requirement already satisfied: pandas in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (2.1.2)\n",
            "Collecting pandasai\n",
            "  Downloading pandasai-1.4.5-py3-none-any.whl.metadata (10 kB)\n",
            "Requirement already satisfied: numpy<2,>=1.22.4 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from pandas) (1.26.1)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from pandas) (2.8.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from pandas) (2023.3.post1)\n",
            "Requirement already satisfied: tzdata>=2022.1 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from pandas) (2023.3)\n",
            "Collecting astor<0.9.0,>=0.8.1 (from pandasai)\n",
            "  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)\n",
            "Collecting duckdb<0.9.0,>=0.8.1 (from pandasai)\n",
            "  Downloading duckdb-0.8.1-cp39-cp39-macosx_11_0_arm64.whl.metadata (737 bytes)\n",
            "Requirement already satisfied: ipython<9.0.0,>=8.13.1 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from pandasai) (8.17.2)\n",
            "Requirement already satisfied: matplotlib<4.0.0,>=3.7.1 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from pandasai) (3.8.1)\n",
            "Collecting openai<0.28.0,>=0.27.5 (from pandasai)\n",
            "  Downloading openai-0.27.10-py3-none-any.whl.metadata (13 kB)\n",
            "Collecting pandas\n",
            "  Downloading pandas-1.5.3-cp39-cp39-macosx_11_0_arm64.whl (11.0 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m11.0/11.0 MB\u001b[0m \u001b[31m43.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m0:01\u001b[0m\n",
            "\u001b[?25hCollecting pydantic<2,>=1 (from pandasai)\n",
            "  Downloading pydantic-1.10.13-cp39-cp39-macosx_11_0_arm64.whl.metadata (149 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m149.6/149.6 kB\u001b[0m \u001b[31m10.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting python-dotenv<2.0.0,>=1.0.0 (from pandasai)\n",
            "  Downloading python_dotenv-1.0.0-py3-none-any.whl (19 kB)\n",
            "Requirement already satisfied: scipy<2.0.0,>=1.9.0 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from pandasai) (1.11.3)\n",
            "Collecting sqlalchemy<2.0.0,>=1.4.49 (from pandasai)\n",
            "  Using cached SQLAlchemy-1.4.50.tar.gz (8.5 MB)\n",
            "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
            "\u001b[?25hRequirement already satisfied: decorator in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from ipython<9.0.0,>=8.13.1->pandasai) (5.1.1)\n",
            "Requirement already satisfied: jedi>=0.16 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from ipython<9.0.0,>=8.13.1->pandasai) (0.19.1)\n",
            "Requirement already satisfied: matplotlib-inline in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from ipython<9.0.0,>=8.13.1->pandasai) (0.1.6)\n",
            "Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from ipython<9.0.0,>=8.13.1->pandasai) (3.0.39)\n",
            "Requirement already satisfied: pygments>=2.4.0 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from ipython<9.0.0,>=8.13.1->pandasai) (2.16.1)\n",
            "Requirement already satisfied: stack-data in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from ipython<9.0.0,>=8.13.1->pandasai) (0.6.3)\n",
            "Requirement already satisfied: traitlets>=5 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from ipython<9.0.0,>=8.13.1->pandasai) (5.13.0)\n",
            "Requirement already satisfied: typing-extensions in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from ipython<9.0.0,>=8.13.1->pandasai) (4.8.0)\n",
            "Requirement already satisfied: exceptiongroup in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from ipython<9.0.0,>=8.13.1->pandasai) (1.1.3)\n",
            "Requirement already satisfied: pexpect>4.3 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from ipython<9.0.0,>=8.13.1->pandasai) (4.8.0)\n",
            "Requirement already satisfied: appnope in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from ipython<9.0.0,>=8.13.1->pandasai) (0.1.3)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (1.2.0)\n",
            "Requirement already satisfied: cycler>=0.10 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (4.44.0)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (1.4.5)\n",
            "Requirement already satisfied: packaging>=20.0 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (23.2)\n",
            "Requirement already satisfied: pillow>=8 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (10.1.0)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (3.1.1)\n",
            "Requirement already satisfied: importlib-resources>=3.2.0 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (6.1.0)\n",
            "Requirement already satisfied: requests>=2.20 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from openai<0.28.0,>=0.27.5->pandasai) (2.31.0)\n",
            "Requirement already satisfied: tqdm in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from openai<0.28.0,>=0.27.5->pandasai) (4.66.1)\n",
            "Requirement already satisfied: aiohttp in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from openai<0.28.0,>=0.27.5->pandasai) (3.8.6)\n",
            "Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)\n",
            "Requirement already satisfied: zipp>=3.1.0 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib<4.0.0,>=3.7.1->pandasai) (3.17.0)\n",
            "Requirement already satisfied: parso<0.9.0,>=0.8.3 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from jedi>=0.16->ipython<9.0.0,>=8.13.1->pandasai) (0.8.3)\n",
            "Requirement already satisfied: ptyprocess>=0.5 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from pexpect>4.3->ipython<9.0.0,>=8.13.1->pandasai) (0.7.0)\n",
            "Requirement already satisfied: wcwidth in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython<9.0.0,>=8.13.1->pandasai) (0.2.9)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from requests>=2.20->openai<0.28.0,>=0.27.5->pandasai) (3.3.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from requests>=2.20->openai<0.28.0,>=0.27.5->pandasai) (3.4)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from requests>=2.20->openai<0.28.0,>=0.27.5->pandasai) (1.26.18)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from requests>=2.20->openai<0.28.0,>=0.27.5->pandasai) (2023.7.22)\n",
            "Requirement already satisfied: attrs>=17.3.0 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai<0.28.0,>=0.27.5->pandasai) (23.1.0)\n",
            "Requirement already satisfied: multidict<7.0,>=4.5 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai<0.28.0,>=0.27.5->pandasai) (6.0.4)\n",
            "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai<0.28.0,>=0.27.5->pandasai) (4.0.3)\n",
            "Requirement already satisfied: yarl<2.0,>=1.0 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai<0.28.0,>=0.27.5->pandasai) (1.9.2)\n",
            "Requirement already satisfied: frozenlist>=1.1.1 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai<0.28.0,>=0.27.5->pandasai) (1.4.0)\n",
            "Requirement already satisfied: aiosignal>=1.1.2 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai<0.28.0,>=0.27.5->pandasai) (1.3.1)\n",
            "Requirement already satisfied: executing>=1.2.0 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython<9.0.0,>=8.13.1->pandasai) (2.0.1)\n",
            "Requirement already satisfied: asttokens>=2.1.0 in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython<9.0.0,>=8.13.1->pandasai) (2.4.1)\n",
            "Requirement already satisfied: pure-eval in /Users/rulz-ai/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython<9.0.0,>=8.13.1->pandasai) (0.2.2)\n",
            "Downloading pandasai-1.4.5-py3-none-any.whl (167 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m167.7/167.7 kB\u001b[0m \u001b[31m11.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading duckdb-0.8.1-cp39-cp39-macosx_11_0_arm64.whl (12.6 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m12.6/12.6 MB\u001b[0m \u001b[31m8.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m:00:01\u001b[0m\n",
            "\u001b[?25hDownloading openai-0.27.10-py3-none-any.whl (76 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m76.5/76.5 kB\u001b[0m \u001b[31m6.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading pydantic-1.10.13-cp39-cp39-macosx_11_0_arm64.whl (2.6 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.6/2.6 MB\u001b[0m \u001b[31m53.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
            "\u001b[?25hBuilding wheels for collected packages: sqlalchemy\n",
            "  Building wheel for sqlalchemy (setup.py) ... \u001b[?25ldone\n",
            "\u001b[?25h  Created wheel for sqlalchemy: filename=SQLAlchemy-1.4.50-cp39-cp39-macosx_10_9_universal2.whl size=1580262 sha256=95e7af22bac5f615e6a6e10b17919bbb31f2b03ebfd441a96097746ab83211bc\n",
            "  Stored in directory: /Users/rulz-ai/Library/Caches/pip/wheels/09/6d/cb/a21a1c3065dd6a71df432d6a35bcfa2319053f9b8d34a6d426\n",
            "Successfully built sqlalchemy\n",
            "Installing collected packages: duckdb, sqlalchemy, python-dotenv, pydantic, astor, pandas, openai, pandasai\n",
            "  Attempting uninstall: sqlalchemy\n",
            "    Found existing installation: SQLAlchemy 2.0.23\n",
            "    Uninstalling SQLAlchemy-2.0.23:\n",
            "      Successfully uninstalled SQLAlchemy-2.0.23\n",
            "  Attempting uninstall: pydantic\n",
            "    Found existing installation: pydantic 2.4.2\n",
            "    Uninstalling pydantic-2.4.2:\n",
            "      Successfully uninstalled pydantic-2.4.2\n",
            "  Attempting uninstall: pandas\n",
            "    Found existing installation: pandas 2.1.2\n",
            "    Uninstalling pandas-2.1.2:\n",
            "      Successfully uninstalled pandas-2.1.2\n",
            "Successfully installed astor-0.8.1 duckdb-0.8.1 openai-0.27.10 pandas-1.5.3 pandasai-1.4.5 pydantic-1.10.13 python-dotenv-1.0.0 sqlalchemy-1.4.50\n"
          ]
        }
      ],
      "source": [
        "!pip install --upgrade pandas pandasai"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "DrrlU4QqDmxl"
      },
      "source": [
        "Now we import the dependencies:"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "id": "ohPMkz4zDqxz"
      },
      "outputs": [],
      "source": [
        "import pandas as pd\n",
        "from pandasai import PandasAI\n",
        "from pandasai.llm.openai import OpenAI"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "JAO_SzlyDr5x"
      },
      "source": [
        "We create a dataframe using pandas:"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "id": "nyRo07nqD08l"
      },
      "outputs": [],
      "source": [
        "df = pd.DataFrame({\n",
        "    \"country\": [\"United States\", \"United Kingdom\", \"France\", \"Germany\", \"Italy\", \"Spain\", \"Canada\", \"Australia\", \"Japan\", \"China\"],\n",
        "    \"gdp\": [21400000, 2940000, 2830000, 3870000, 2160000, 1350000, 1780000, 1320000, 516000, 14000000],\n",
        "    \"happiness_index\": [7.3, 7.2, 6.5, 7.0, 6.0, 6.3, 7.3, 7.3, 5.9, 5.0]\n",
        "})"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "WRKWFWSGD1tB"
      },
      "source": [
        "We instanciate the llm (in this case OpenAI). Remember to change the API key with you OpenAI api key."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "id": "MhByl8oxEJFH"
      },
      "outputs": [],
      "source": [
        "OPENAI_API_KEY = \"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\"\n",
        "llm = OpenAI(api_token=OPENAI_API_KEY)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "aeTOQettEfWT"
      },
      "source": [
        "Then we instantiate PandasAI with the provided large language model and we run it, passing the dataframe and the prompt"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 206
        },
        "id": "HZnx0V18EkzS",
        "outputId": "f9c539b5-fd75-423f-e17d-55da0ebd809b"
      },
      "outputs": [
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "/Users/rulz-ai/Library/Python/3.9/lib/python/site-packages/pandasai/__init__.py:146: UserWarning: `PandasAI` (class) is deprecated since v1.0 and will be removed in a future release. Please use `SmartDataframe` instead.\n",
            "  warnings.warn(\n"
          ]
        },
        {
          "data": {
            "text/plain": [
              "'Unfortunately, I was not able to answer your question, because of the following error:\\n\\nThe OpenAI account associated with this API key has been deactivated. If you are the developer for this OpenAI app, please check your email for more information. If you are seeing this error while using another app or site, please reach out to them for more help.\\n'"
            ]
          },
          "execution_count": 5,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "pandas_ai = PandasAI(llm)\n",
        "pandas_ai.run(df, prompt='What are the 5 happiest countries')"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "D2BzTCNBb3-6"
      },
      "source": [
        "You can also show a chart, for example:"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 6,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 472
        },
        "id": "XsCB5S4Nb9QK",
        "outputId": "4e2a126a-a55d-4b41-819f-91e2d598f8e2"
      },
      "outputs": [
        {
          "data": {
            "text/plain": [
              "'Unfortunately, I was not able to answer your question, because of the following error:\\n\\nThe OpenAI account associated with this API key has been deactivated. If you are the developer for this OpenAI app, please check your email for more information. If you are seeing this error while using another app or site, please reach out to them for more help.\\n'"
            ]
          },
          "execution_count": 6,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "pandas_ai.run(df, \"Plot the histogram of countries showing for each the gpd, using different colors for each bar\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "hiRupKR1u6kK"
      },
      "source": [
        "You can also ask for questions involving multiple dataframes.\n",
        "For example:"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 7,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 35
        },
        "id": "G06Sb9Niu_bm",
        "outputId": "4d12fcd4-3ffc-4349-c231-2ea0a424dff0"
      },
      "outputs": [
        {
          "data": {
            "text/plain": [
              "'Unfortunately, I was not able to answer your question, because of the following error:\\n\\nThe OpenAI account associated with this API key has been deactivated. If you are the developer for this OpenAI app, please check your email for more information. If you are seeing this error while using another app or site, please reach out to them for more help.\\n'"
            ]
          },
          "execution_count": 7,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "employees_data = {\n",
        "    'EmployeeID': [1, 2, 3, 4, 5],\n",
        "    'Name': ['John', 'Emma', 'Liam', 'Olivia', 'William'],\n",
        "    'Department': ['HR', 'Sales', 'IT', 'Marketing', 'Finance']\n",
        "}\n",
        "\n",
        "salaries_data = {\n",
        "    'EmployeeID': [1, 2, 3, 4, 5],\n",
        "    'Salary': [5000, 6000, 4500, 7000, 5500]\n",
        "}\n",
        "\n",
        "employees_df = pd.DataFrame(employees_data)\n",
        "salaries_df = pd.DataFrame(salaries_data)\n",
        "\n",
        "pandas_ai([employees_df, salaries_df], \"Who gets paid the most?\")"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "include_colab_link": true,
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.9.6"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
